#!/usr/bin/env python3
"""Build prototype.html — a single self-contained clickable prototype.

Every component is embedded verbatim inside a <script type="text/plain"> block and
mounted into an iframe via srcdoc when you navigate to it. The iframe gives each
component its own document, so there is no CSS scoping to do and each component's
own <script> keeps working — which is why this does not reuse build-reviews.py's
`.mk` scoping path.

Emits:  prototype.html   (next to the components, ~4.5 MB, opens over file://)
Run:    python3 _assets/build-prototype.py
"""
import json
import os
import re

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
OUT = os.path.join(ROOT, "prototype.html")

# Components that are specimen sheets, not screens a member can navigate to.
KITS = {"foundations", "forms", "dialogs", "sheets", "states", "comments"}
WIDE = {"desktop-shell", "foundations"}


def frames_of(markup):
    """[(title, index)] for each <section class="frame">, or [] for a single-page component.

    Scoped to <main> deliberately: a component's own <script> can mention
    `<section class="frame">` in a comment, and counting that produced a phantom
    screen the client could navigate to and see raw JavaScript in.
    """
    m = re.search(r"<main[^>]*>(.*)</main>", markup, re.S)
    markup = m.group(1) if m else markup
    out = []
    for i, m in enumerate(re.finditer(r'<section[^>]*class="[^"]*\bframe\b[^"]*"[^>]*>', markup)):
        t = re.search(r'data-title="([^"]*)"', m.group(0))
        out.append(t.group(1) if t else f"Screen {i + 1}")
    return out


def desktop_shot_items():
    """Screenshot pages generated by build-desktop-shots.py."""
    p = os.path.join(HERE, "desktop-shots-manifest.json")
    if not os.path.exists(p):
        return []
    data = json.load(open(p, encoding="utf-8"))
    items = []
    for it in data.get("items", []):
        items.append({
            "slug": it["slug"],
            "title": it["title"],
            "figma": it.get("figma", "designed"),
            "wide": True,
            "desktopApp": it.get("app", "fan"),
        })
        WIDE.add(it["slug"])
    return items


def load():
    man = json.load(open(os.path.join(HERE, "manifest.json")))
    shot_items = desktop_shot_items()
    for g in man["groups"]:
        if g.get("name") != "Desktop":
            continue
        kept = [it for it in g.get("items", []) if it.get("slug") == "desktop-shell"]
        order = {"fan": 0, "management": 1, "dsc": 2}
        shot_items.sort(key=lambda it: (order.get(it.get("desktopApp"), 9), it["title"].lower()))
        g["items"] = kept + [
            {k: v for k, v in it.items() if k != "desktopApp"} for it in shot_items
        ]
        g["note"] = (
            "Three desktop products from Branding -Desktop screenshots. "
            "One page per tab — Fan app, Management, DSC Labs."
        )
        break

    app_by_slug = {it["slug"]: it.get("desktopApp", "") for it in shot_items}
    app_by_slug["desktop-shell"] = "fan"

    groups, docs = [], {}
    for g in man["groups"]:
        items = []
        for it in g["items"]:
            slug = it["slug"]
            path = os.path.join(ROOT, f"{slug}.html")
            if not os.path.exists(path):
                continue
            markup = open(path, encoding="utf-8").read()
            docs[slug] = markup
            items.append({
                "slug": slug,
                "title": it["title"],
                "figma": it.get("figma", "new"),
                "kit": slug in KITS,
                "wide": slug in WIDE or it.get("wide", False) or slug.startswith("desktop-"),
                "frames": frames_of(markup),
                "status": it.get("status", ""),
                "why": it.get("why", ""),
                "proposalFrames": it.get("proposalFrames", {}),
                "desktopApp": app_by_slug.get(slug, ""),
            })
        if items:
            groups.append({"name": g["name"], "note": g.get("note", ""), "items": items})
    return groups, docs


def flows():
    p = os.path.join(HERE, "flows.json")
    return json.load(open(p)) if os.path.exists(p) else {}


def journeys():
    """Named, ordered paths through the screens, for guided playback.

    Clicking around a 174-screen prototype tells a client very little. A journey is
    the unit they actually care about — "a member proposes an idea and it lapses" —
    so the prototype can step through one with the arrow keys and say, at each step,
    what the member is doing and why.
    """
    p = os.path.join(HERE, "journeys.json")
    if not os.path.exists(p):
        return []
    data = json.load(open(p))
    return data.get("groups", data) if isinstance(data, dict) else data


# --------------------------------------------------------------------- shell
SHELL_CSS = r"""
*{box-sizing:border-box}
html,body{margin:0;height:100%}
body{
  background:#EDEFE9;color:#14170F;
  font:400 14px/1.5 ui-sans-serif,-apple-system,"Segoe UI",Roboto,Helvetica,Arial,sans-serif;
  -webkit-font-smoothing:antialiased;
}
:root{
  --paper:#EDEFE9; --panel:#E4E7DE; --rule:#CFD4C7; --rule-soft:#DCE0D5;
  --ink:#14170F; --ink-2:#545B4B; --ink-3:#7C8471; --stage:#0B0D08; --acid:#9BE222;
  --mono:ui-monospace,SFMono-Regular,Menlo,Consolas,monospace;
  --nav-w:250px; --notes-w:330px;
}
@media (prefers-color-scheme:dark){
  :root{--paper:#14170F;--panel:#1B1F17;--rule:#2E3428;--rule-soft:#242A1E;
        --ink:#F1F3EC;--ink-2:#A9B29C;--ink-3:#7C8471}
}
.app{display:grid;grid-template-columns:var(--nav-w) minmax(0,1fr) var(--notes-w);height:100%}
@media (max-width:1180px){
  .app{grid-template-columns:210px minmax(0,1fr);}
  .notes{display:none}
  .notes.open{display:flex;position:fixed;right:0;top:0;bottom:0;width:330px;z-index:60;
              box-shadow:-18px 0 48px rgba(0,0,0,.22)}
}
@media (max-width:820px){ .app{grid-template-columns:1fr} .nav{display:none} .nav.open{display:flex;position:fixed;left:0;top:0;bottom:0;width:250px;z-index:60} }

/* ---------- left nav ---------- */
.nav{border-right:1px solid var(--rule);background:var(--panel);display:flex;flex-direction:column;min-height:0}
.nav__head{padding:16px 16px 10px;border-bottom:1px solid var(--rule)}
.brand{font-family:var(--mono);font-size:10px;letter-spacing:.18em;text-transform:uppercase;color:var(--ink-3);margin:0 0 8px}
.nav__title{margin:0 0 10px;font-size:16px;font-weight:700;letter-spacing:-.01em}
.find{width:100%;height:32px;padding:0 10px;border:1px solid var(--rule);border-radius:8px;
      background:var(--paper);color:var(--ink);font:inherit;font-size:12.5px}
.find:focus{outline:2px solid var(--acid);outline-offset:1px}
.nav__scroll{flex:1;overflow-y:auto;padding:10px 8px 28px;overscroll-behavior:contain}
.grp{margin:0 0 14px}
.grp__t{margin:8px 8px 5px;font-family:var(--mono);font-size:9.5px;letter-spacing:.16em;
        text-transform:uppercase;color:var(--ink-3)}
.cmp{margin:0 0 1px}
.cmp__b{
  display:flex;align-items:center;gap:7px;width:100%;padding:6px 8px;border:0;border-radius:7px;
  background:none;color:var(--ink);font:inherit;font-size:13px;text-align:left;cursor:pointer;
}
.cmp__b:hover{background:var(--rule-soft)}
.cmp__b[aria-expanded="true"]{font-weight:650}
.cmp__cnt{margin-left:auto;font-family:var(--mono);font-size:9.5px;color:var(--ink-3)}
.cmp__k{font-family:var(--mono);font-size:8.5px;letter-spacing:.1em;color:var(--ink-3);
        border:1px solid var(--rule);border-radius:4px;padding:1px 3px}
.frames{list-style:none;margin:1px 0 4px;padding:0 0 0 8px;border-left:1px solid var(--rule)}
.frames[hidden]{display:none}
.fr__b{
  display:flex;gap:8px;align-items:center;width:100%;padding:5px 8px;border:0;border-radius:6px;
  background:none;color:var(--ink-2);font:inherit;font-size:12.5px;text-align:left;cursor:pointer;
}
.fr__b:hover{background:var(--rule-soft);color:var(--ink)}
.fr__b[aria-current="true"]{background:var(--acid);color:#0B0E06;font-weight:650}
.fr__n{font-family:var(--mono);font-size:9.5px;opacity:.75}
.fr__dot{margin-left:auto;width:6px;height:6px;border-radius:50%;background:#E2564A;flex:none}

/* ---------- stage ---------- */
.stage{display:flex;flex-direction:column;min-width:0;min-height:0}
.bar{display:flex;align-items:center;gap:10px;padding:12px 18px;border-bottom:1px solid var(--rule);flex:none}
.bar h1{margin:0;font-size:15px;font-weight:650;letter-spacing:-.01em;white-space:nowrap;
        overflow:hidden;text-overflow:ellipsis}
.bar .crumb{font-family:var(--mono);font-size:10px;letter-spacing:.12em;text-transform:uppercase;color:var(--ink-3)}
.spacer{flex:1}
.btn{
  height:30px;padding:0 11px;border:1px solid var(--rule);border-radius:8px;background:var(--paper);
  color:var(--ink);font:inherit;font-size:12.5px;cursor:pointer;display:inline-flex;align-items:center;gap:6px;
}
.btn:hover{border-color:var(--ink-3)}
.btn--go{background:var(--acid);border-color:var(--acid);color:#0B0E06;font-weight:600}
.btn[disabled]{opacity:.4;cursor:default}
.states{display:flex;gap:6px;flex-wrap:wrap;padding:10px 18px;border-bottom:1px solid var(--rule);
        background:var(--panel);flex:none}
.states:empty{display:none}
.st{
  height:27px;padding:0 10px;border:1px solid var(--rule);border-radius:999px;background:var(--paper);
  color:var(--ink-2);font:inherit;font-size:12px;cursor:pointer;display:inline-flex;align-items:center;gap:6px;
}
.st:hover{color:var(--ink)}
.st[aria-current="true"]{background:var(--acid);border-color:var(--acid);color:#0B0E06;font-weight:650}
.st__n{font-family:var(--mono);font-size:9.5px;opacity:.8}
.hold{flex:1;min-height:0;display:grid;place-items:center;padding:22px;background:
   radial-gradient(circle at 50% 0%,rgba(0,0,0,.05),transparent 60%)}
/* height is fixed and the whole device is scaled by fit(); a max-height here would
   squash the frame instead of scaling it, because the iframe inside is height:100% */
.dev{
  position:relative;width:390px;height:812px;border-radius:44px;padding:10px;
  background:#0B0D08;box-shadow:0 30px 70px rgba(0,0,0,.34),0 0 0 1px rgba(255,255,255,.07) inset;
  flex:none;transform-origin:center center;
}
.dev--wide{width:1180px;height:760px;border-radius:16px;padding:8px}
.dev__i{position:absolute;left:50%;top:20px;transform:translateX(-50%);width:98px;height:26px;
        border-radius:999px;background:#000;z-index:4;pointer-events:none}
.dev--wide .dev__i{display:none}
.dev iframe{width:100%;height:100%;border:0;border-radius:35px;background:#030401;display:block}
.dev--wide iframe{border-radius:9px}
.hint{position:absolute;left:0;right:0;bottom:-30px;text-align:center;font-size:11.5px;color:var(--ink-3)}

/* ---------- notes ---------- */
.notes{border-left:1px solid var(--rule);background:var(--panel);display:flex;flex-direction:column;min-height:0}
.notes__h{padding:14px 16px 11px;border-bottom:1px solid var(--rule);display:flex;align-items:center;gap:8px}
.notes__h h2{margin:0;font-size:13px;font-weight:650}
.notes__for{font-family:var(--mono);font-size:9.5px;letter-spacing:.1em;text-transform:uppercase;
            color:var(--ink-3);padding:0 16px 10px;border-bottom:1px solid var(--rule)}
.note{
  margin:0;padding:11px 16px;border-bottom:1px solid var(--rule);background:var(--paper);
  font-size:12px;line-height:1.45;color:var(--ink-2);max-height:190px;overflow-y:auto;
}
.note::before{
  content:"Design note";display:block;font-family:var(--mono);font-size:9px;letter-spacing:.14em;
  text-transform:uppercase;color:var(--ink-3);margin-bottom:4px;
}
.notes__l{flex:1;overflow-y:auto;padding:12px 16px;display:flex;flex-direction:column;gap:9px;overscroll-behavior:contain}
.cmt{border:1px solid var(--rule);border-radius:10px;padding:9px 11px;background:var(--paper)}
.cmt__m{display:flex;gap:7px;align-items:center;font-family:var(--mono);font-size:9.5px;color:var(--ink-3);margin-bottom:5px}
.cmt__x{margin-left:auto;border:0;background:none;color:var(--ink-3);cursor:pointer;font-size:14px;line-height:1;padding:0 2px}
.cmt__x:hover{color:#E2564A}
.cmt p{margin:0;font-size:13px;white-space:pre-wrap;word-wrap:break-word}
.cmt.done{opacity:.5}
.cmt.done p{text-decoration:line-through}
.none{color:var(--ink-3);font-size:12.5px;margin:2px 0}
.notes__f{border-top:1px solid var(--rule);padding:11px 16px 14px;display:flex;flex-direction:column;gap:8px}
.notes__f textarea{
  width:100%;min-height:76px;resize:vertical;padding:9px 10px;border:1px solid var(--rule);
  border-radius:9px;background:var(--paper);color:var(--ink);font:inherit;font-size:13px;
}
.notes__f textarea:focus{outline:2px solid var(--acid);outline-offset:1px}
.who{height:29px;padding:0 9px;border:1px solid var(--rule);border-radius:8px;background:var(--paper);
     color:var(--ink);font:inherit;font-size:12.5px;flex:1;min-width:0}
.row{display:flex;gap:7px;align-items:center}

/* ---------- coverage sheet ---------- */
.sheet{max-width:860px;margin:0 auto;padding:26px 24px 70px;overflow-y:auto;height:100%;width:100%}
.sheet h2{margin:0 0 6px;font-size:22px;letter-spacing:-.02em}
.sheet h3{margin:26px 0 8px;font-size:14px}
.sheet p{margin:0 0 12px;max-width:70ch;color:var(--ink-2)}
.sheet table{border-collapse:collapse;width:100%;font-size:13px;margin:8px 0 4px}
.sheet th,.sheet td{text-align:left;padding:8px 10px;border-bottom:1px solid var(--rule-soft);vertical-align:top}
.sheet thead th{font-family:var(--mono);font-size:9.5px;letter-spacing:.12em;text-transform:uppercase;color:var(--ink-3)}
.sheet code{font-family:var(--mono);font-size:12px;background:var(--panel);padding:1px 4px;border-radius:4px}
.tag{display:inline-block;font-family:var(--mono);font-size:9px;letter-spacing:.1em;text-transform:uppercase;
     border:1px solid var(--rule);border-radius:4px;padding:1px 5px;color:var(--ink-3)}
.tag--no{border-color:#E2564A;color:#E2564A}


/* ---------- voice + dictation ---------- */
.vrow{display:grid;grid-template-columns:1fr 1fr;gap:8px}
.vbtn{
  display:flex;align-items:center;justify-content:center;gap:8px;
  height:52px;padding:0 12px;border:1.5px solid var(--rule);border-radius:12px;
  background:var(--paper);color:var(--ink);font:inherit;font-size:14.5px;font-weight:600;
  cursor:pointer;transition:background .12s,border-color .12s;
}
.vbtn:hover{border-color:var(--ink-3)}
.vbtn svg{width:20px;height:20px;flex:none}
.vbtn:focus-visible{outline:2px solid var(--acid);outline-offset:2px}
.vbtn[disabled]{opacity:.45;cursor:default}
.vbtn.on{background:#E2564A;border-color:#E2564A;color:#fff}
.vbtn.on svg{animation:vpulse 1.1s ease-in-out infinite}
@keyframes vpulse{0%,100%{opacity:1}50%{opacity:.35}}
@media (prefers-reduced-motion:reduce){.vbtn.on svg{animation:none}}
.btn--add{height:40px;font-size:14px;padding:0 16px}
.vhint{margin:0;font-size:11.5px;line-height:1.4;color:var(--ink-3)}
.pend{display:flex;align-items:center;gap:8px}
.pend audio{flex:1;min-width:0;height:34px}
.cmt__play{
  display:inline-flex;align-items:center;gap:6px;margin-top:7px;height:32px;padding:0 10px;
  border:1px solid var(--rule);border-radius:8px;background:var(--panel);
  color:var(--ink);font:inherit;font-size:12.5px;cursor:pointer;
}
.cmt__play:hover{border-color:var(--ink-3)}
.cmt__play svg{width:13px;height:13px}

/* ---------- journeys ---------- */
.jbar{display:flex;align-items:center;gap:10px;padding:9px 18px;flex:none;
  border-bottom:1px solid var(--rule);background:var(--acid);color:#0B0E06}
.jbar .btn{background:rgba(255,255,255,.82);border-color:rgba(0,0,0,.14);color:#0B0E06}
.jbar .btn--go{background:#0B0E06;border-color:#0B0E06;color:var(--acid)}
.jbar__t{display:flex;flex-direction:column;line-height:1.25;min-width:0}
.jbar__t b{font-size:13.5px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}
.jbar__t span{font-family:var(--mono);font-size:9.5px;letter-spacing:.1em;text-transform:uppercase;opacity:.72}
.jstep{font-family:var(--mono);font-size:11px;letter-spacing:.08em;white-space:nowrap}
.jpick{position:absolute;inset:0;z-index:70;background:var(--paper);display:flex;flex-direction:column}
.jpick__h{display:flex;align-items:center;gap:10px;padding:12px 18px;border-bottom:1px solid var(--rule)}
.jpick__h b{font-size:15px}
.jpick__h .find{max-width:280px}
.jpick__l{flex:1;overflow-y:auto;padding:14px 18px 40px}
.jgrp{margin:0 0 18px}
.jgrp__t{margin:0 0 8px;font-family:var(--mono);font-size:10px;letter-spacing:.15em;
  text-transform:uppercase;color:var(--ink-3)}
.jrow{display:flex;align-items:baseline;gap:10px;width:100%;padding:9px 11px;margin-bottom:3px;
  border:1px solid var(--rule);border-radius:9px;background:var(--panel);
  font:inherit;text-align:left;cursor:pointer}
.jrow:hover{border-color:var(--ink-3)}
.jrow__n{font-size:13.5px;font-weight:600}
.jrow__w{font-family:var(--mono);font-size:9.5px;letter-spacing:.09em;text-transform:uppercase;color:var(--ink-3)}
.jrow__c{margin-left:auto;font-family:var(--mono);font-size:10px;color:var(--ink-3);white-space:nowrap}
.jrow__y{display:block;margin-top:3px;font-size:12px;color:var(--ink-2)}
.jnote{margin:0;padding:11px 16px;border-bottom:1px solid var(--rule);
  background:var(--acid);color:#0B0E06;font-size:12.5px;line-height:1.45}
.jnote::before{content:"This step";display:block;font-family:var(--mono);font-size:9px;
  letter-spacing:.13em;text-transform:uppercase;opacity:.7;margin-bottom:3px}

/* ---------- proposal marking ----------
   A screen with no counterpart in lib/ is a proposal, not a rebrand. These read as
   finished as everything else, so they must be labelled or the client will assume the
   journey exists in the app today. Amber, never the acid — acid means "you are here". */
.pflag{
  flex:none;font-family:var(--mono);font-size:9.5px;letter-spacing:.12em;text-transform:uppercase;
  color:#8A5A12;background:#F6E2B6;border:1px solid #E3C583;border-radius:5px;padding:3px 7px;
}
@media (prefers-color-scheme:dark){.pflag{color:#F2CE86;background:#3A2E12;border-color:#5D4718}}
.pwhy{
  margin:0;padding:10px 16px;border-bottom:1px solid var(--rule);
  background:#F6E2B6;color:#5C3C0B;font-size:12px;line-height:1.45;
}
@media (prefers-color-scheme:dark){.pwhy{background:#332809;color:#F0D49A}}
.pwhy::before{
  content:"Proposal — not in the app";display:block;font-family:var(--mono);font-size:9px;
  letter-spacing:.13em;text-transform:uppercase;opacity:.75;margin-bottom:4px;
}
.fr__p,.cmp__p{
  font-family:var(--mono);font-size:8.5px;letter-spacing:.08em;color:#8A5A12;
  background:#F6E2B6;border-radius:3px;padding:1px 4px;flex:none;
}
@media (prefers-color-scheme:dark){.fr__p,.cmp__p{color:#F2CE86;background:#3A2E12}}
.st--p{border-style:dashed}
.hidden{display:none!important}

/* ---------- access gate ---------- */
body:not(.unlocked) .app{visibility:hidden;pointer-events:none}
.gate{
  position:fixed;inset:0;z-index:200;display:grid;place-items:center;padding:24px;
  background:rgba(11,13,8,.55);backdrop-filter:blur(8px);-webkit-backdrop-filter:blur(8px);
}
body.unlocked .gate{display:none}
.gate__card{
  width:min(400px,100%);padding:28px 26px 24px;border:1px solid var(--rule);
  border-radius:16px;background:var(--paper);box-shadow:0 28px 60px rgba(0,0,0,.28);
}
.gate__brand{
  margin:0 0 8px;font-family:var(--mono);font-size:10px;letter-spacing:.18em;
  text-transform:uppercase;color:var(--ink-3);
}
.gate__card h2{margin:0 0 8px;font-size:22px;letter-spacing:-.02em;font-weight:750}
.gate__card p{margin:0 0 18px;color:var(--ink-2);font-size:14px;line-height:1.45}
.gate__card label{
  display:block;margin:0 0 6px;font-family:var(--mono);font-size:10px;
  letter-spacing:.12em;text-transform:uppercase;color:var(--ink-3);
}
.gate__card input[type="password"]{
  width:100%;height:42px;padding:0 12px;margin:0 0 10px;border:1px solid var(--rule);
  border-radius:10px;background:var(--panel);color:var(--ink);font:inherit;font-size:15px;
}
.gate__card input[type="password"]:focus{outline:2px solid var(--acid);outline-offset:1px}
.gate__err{margin:0 0 12px;min-height:1.2em;font-size:13px;color:#E2564A}
.gate__card .btn--go{width:100%;height:42px;justify-content:center;font-size:14px}

/* ---------- mobile / desktop platform switch ---------- */
.plat{
  display:grid;grid-template-columns:1fr 1fr;gap:3px;margin:0 0 10px;padding:3px;
  border:1px solid var(--rule);border-radius:10px;background:var(--paper);
}
.plat__b{
  height:30px;border:0;border-radius:7px;background:transparent;color:var(--ink-2);
  font:inherit;font-size:12px;font-weight:600;cursor:pointer;
}
.plat__b:hover{color:var(--ink)}
.plat__b[aria-pressed="true"]{background:var(--acid);color:#0B0E06}
.dapp{
  display:none;grid-template-columns:1fr 1fr 1fr;gap:3px;margin:0 0 10px;padding:3px;
  border:1px solid var(--rule);border-radius:10px;background:var(--paper);
}
body[data-platform="desktop"] .dapp{display:grid}
.dapp__b{
  height:30px;border:0;border-radius:7px;background:transparent;color:var(--ink-2);
  font:inherit;font-size:11px;font-weight:600;cursor:pointer;padding:0 4px;
}
.dapp__b:hover{color:var(--ink)}
.dapp__b[aria-pressed="true"]{background:var(--acid);color:#0B0E06}
"""


def build():
    groups, docs = load(), None
    groups, docs = load()
    flow = flows()
    jour = journeys()

    parts = [
        "<!DOCTYPE html>",
        '<html lang="en">',
        "<head>",
        '<meta charset="utf-8">',
        '<meta name="viewport" content="width=device-width, initial-scale=1">',
        "<title>SportsHeist — prototype</title>",
        f"<style>{SHELL_CSS}</style>",
        "</head>",
        "<body>",
        '<div class="gate" id="gate" role="dialog" aria-modal="true" aria-labelledby="gateTitle">',
        '  <form class="gate__card" id="gateForm" autocomplete="off">',
        '    <p class="gate__brand">SportsHeist</p>',
        '    <h2 id="gateTitle">Client review</h2>',
        '    <p>Enter the access password to open the prototype and leave comments on each screen.</p>',
        '    <label for="gatePw">Password</label>',
        '    <input id="gatePw" name="password" type="password" required autofocus '
        'placeholder="Password" autocomplete="current-password">',
        '    <p class="gate__err" id="gateErr" aria-live="polite"></p>',
        '    <button class="btn btn--go" type="submit">Open prototype</button>',
        "  </form>",
        "</div>",
        '<div class="app">',

        '<nav class="nav" id="nav">',
        '  <div class="nav__head">',
        '    <p class="brand">SportsHeist</p>',
        '    <h1 class="nav__title">Prototype</h1>',
        '    <div class="plat" role="tablist" aria-label="Platform">'
        '<button class="plat__b" type="button" role="tab" id="platMobile" aria-pressed="true">Mobile</button>'
        '<button class="plat__b" type="button" role="tab" id="platDesktop" aria-pressed="false">Desktop</button>'
        '</div>',
        '    <div class="dapp" role="tablist" aria-label="Desktop app" id="dapp">'
        '<button class="dapp__b" type="button" role="tab" data-dapp="fan" aria-pressed="true">Fan app</button>'
        '<button class="dapp__b" type="button" role="tab" data-dapp="management" aria-pressed="false">Management</button>'
        '<button class="dapp__b" type="button" role="tab" data-dapp="dsc" aria-pressed="false">DSC Labs</button>'
        '</div>',
        '    <input class="find" id="find" type="search" placeholder="Find a screen…" aria-label="Find a screen">',
        "  </div>",
        '  <div class="nav__scroll" id="navlist"></div>',
        "</nav>",

        '<main class="stage">',
        '  <div class="bar">',
        '    <div><div class="crumb" id="crumb">—</div><h1 id="title">—</h1></div>',
        '    <span class="pflag hidden" id="pflag" title="No counterpart in the app\'s code">'
        'Proposal</span>',
        '    <span class="spacer"></span>',
        '    <button class="btn" id="prev" title="Previous screen (←)">←</button>',
        '    <button class="btn" id="next" title="Next screen (→)">→</button>',
        '    <button class="btn btn--go" id="jbtn">Journeys</button>',
        '    <button class="btn" id="cov">Coverage</button>',
        '    <button class="btn" id="exp">Export comments</button>',
        "  </div>",
        '  <div class="jbar hidden" id="jbar">',
        '    <button class="btn" id="jx" title="Leave this journey">✕</button>',
        '    <div class="jbar__t"><b id="jname">—</b><span id="jwho"></span></div>',
        '    <span class="spacer"></span>',
        '    <span class="jstep" id="jstep">—</span>',
        '    <button class="btn" id="jprev" title="Previous step (←)">←</button>',
        '    <button class="btn btn--go" id="jnext" title="Next step (→)">Next →</button>',
        '  </div>',
        '  <div class="states" id="states"></div>',
        '  <div class="hold" id="hold">',
        '    <div class="dev" id="dev"><div class="dev__i"></div><iframe id="fr" title="Screen"></iframe>',
        '      <p class="hint" id="hint"></p>',
        "    </div>",
        '    <div class="sheet hidden" id="sheet"></div>',
        "  </div>",
        '  <div class="jpick hidden" id="jpick">',
        '    <div class="jpick__h"><b>Journeys</b>'
        '<input class="find" id="jfind" type="search" placeholder="Find a journey…">'
        '<button class="btn" id="jclose">Close</button></div>',
        '    <div class="jpick__l" id="jlist"></div>',
        '  </div>',
        "</main>",

        '<aside class="notes" id="notes">',
        '  <div class="notes__h"><h2>Comments</h2><span class="spacer"></span>'
        '<button class="btn" id="allc" title="Show every comment">All</button></div>',
        '  <p class="notes__for" id="for">—</p>',
        '  <p class="jnote hidden" id="jnote"></p>',
        '  <p class="pwhy hidden" id="pwhy"></p>',
        '  <p class="note hidden" id="note"></p>',
        '  <div class="notes__l" id="list"></div>',
        '  <div class="notes__f">',
        '    <textarea id="txt" placeholder="Type here, or use Dictate — you can edit either before adding."></textarea>',
        '    <div class="vrow">',
        '      <button class="vbtn" id="dictate" type="button">'
        '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.9" '
        'stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">'
        '<rect x="9" y="2.5" width="6" height="11" rx="3"/>'
        '<path d="M5 11a7 7 0 0 0 14 0M12 18v3.5"/></svg>'
        '<span id="dictateL">Dictate</span></button>',
        '      <button class="vbtn" id="record" type="button" '
        'title="Records audio and a live transcript — the transcript travels in the export; the audio itself stays in this browser.">'
        '<svg viewBox="0 0 24 24" aria-hidden="true"><circle cx="12" cy="12" r="7" fill="currentColor"/></svg>'
        '<span id="recordL">Record</span></button>',
        '    </div>',
        '    <p class="vhint hidden" id="vhint"></p>',
        '    <div class="pend hidden" id="pend">'
        '<audio id="pendA" controls></audio>'
        '<button class="btn" id="pendX" title="Discard this recording">Discard</button></div>',
        '    <div class="row"><input class="who" id="who" placeholder="Your name">'
        '<button class="btn btn--go btn--add" id="add">Add comment</button></div>',
        "  </div>",
        "</aside>",
        "</div>",
    ]

    # component sources, escaped so an inner </script> can't close the block
    for slug, markup in docs.items():
        safe = markup.replace("</script>", "<\\/script>")
        parts.append(f'<script type="text/plain" data-doc="{slug}">{safe}</script>')

    parts.append(f"<script>const GROUPS={json.dumps(groups)};const FLOWS={json.dumps(flow)};const JOURNEYS={json.dumps(jour)};</script>")
    parts.append("<script>" + APP_JS + "</script>")
    parts += ["</body>", "</html>"]

    html = "\n".join(parts)
    open(OUT, "w", encoding="utf-8").write(html)

    n_frames = sum(len(i["frames"]) or 1 for g in groups for i in g["items"])
    n_cmp = sum(len(g["items"]) for g in groups)
    print(f"  prototype.html   {len(html)/1048576:.1f} MB   {n_cmp} components · {n_frames} screens")
    wired = sum(len(v) for v in flow.values())
    print(f"  flows.json       {len(flow)} screens wired · {wired} hotspots"
          if flow else "  flows.json       absent — nav-only prototype")


# --------------------------------------------------------------------- app js
APP_JS = r"""
const $=s=>document.querySelector(s);

/* access gate — lightweight client-side check for the review link */
(function(){
  const GATE_KEY='sportsheist-prototype-unlocked';
  const PASS='Cabramatta@123';
  const unlock=()=>{
    document.body.classList.add('unlocked');
    try{sessionStorage.setItem(GATE_KEY,'1')}catch(e){}
    const pw=$('#gatePw'); if(pw) pw.value='';
  };
  try{ if(sessionStorage.getItem(GATE_KEY)==='1') unlock(); }catch(e){}
  const form=$('#gateForm');
  if(form){
    form.addEventListener('submit',e=>{
      e.preventDefault();
      const v=($('#gatePw')||{}).value||'';
      if(v===PASS){ $('#gateErr').textContent=''; unlock(); }
      else{
        $('#gateErr').textContent='That password is incorrect.';
        const pw=$('#gatePw'); if(pw){ pw.focus(); pw.select(); }
      }
    });
  }
})();

const DOCS={};
document.querySelectorAll('script[data-doc]').forEach(s=>{
  DOCS[s.dataset.doc]=s.textContent.replace(/<\\\/script>/g,'<\/script>');
});

/* flat screen list ------------------------------------------------------- */
const SCREENS=[];
GROUPS.forEach(g=>g.items.forEach(it=>{
  const fs=it.frames.length?it.frames:[it.title];
  fs.forEach((t,i)=>{
    /* Agents are adding "… · as shipped" / "… · shipped today" frames INTO proposal components — the whole-component
       flag would then label real, shipped behaviour as a proposal, which is the exact error
       the flag exists to prevent. A frame that says it is shipped always wins over it. */
    const shipped=/\bshipped\b/i.test(t);
    const why=shipped ? '' : (it.status==='proposal' ? it.why : (it.proposalFrames||{})[t]||'');
    SCREENS.push({
      id:it.frames.length?`${it.slug}/${i}`:it.slug,
      slug:it.slug, idx:it.frames.length?i:-1, frame:t,
      comp:it.title, group:g.name, kit:it.kit, wide:it.wide,
      proposal:!!why, why:why,
      desktopApp:it.desktopApp||''
    });
  });
}));
const byId=Object.fromEntries(SCREENS.map(s=>[s.id,s]));

/* comments --------------------------------------------------------------- */
const KEY='sportsheist-prototype-comments';
let DB={}; try{DB=JSON.parse(localStorage.getItem(KEY)||'{}')}catch(e){DB={}}
const save=()=>{try{localStorage.setItem(KEY,JSON.stringify(DB))}catch(e){
  alert('Could not save — browser storage is full or blocked. Export before you lose anything.')}};
const count=id=>(DB[id]||[]).filter(c=>!c.done).length;

/* state ------------------------------------------------------------------ */
let cur=null, showingAll=false;

/* Mobile ↔ Desktop, then Fan app / Management / DSC Labs on desktop. */
const PLATFORM_KEY='sportsheist-prototype-platform';
const DAPP_KEY='sportsheist-prototype-dapp';
const MOBILE_HOME='war-room/0';
const DESKTOP_APPS={
  fan:{home:'desktop-fan-war-room/0', match:s=>s.desktopApp==='fan'||s.slug==='desktop-shell'||s.slug.startsWith('desktop-fan-')},
  management:{home:'desktop-management-dashboard/0', match:s=>s.desktopApp==='management'||s.slug.startsWith('desktop-management-')},
  dsc:{home:'desktop-dsc-login/0', match:s=>s.desktopApp==='dsc'||s.slug.startsWith('desktop-dsc-')}
};
const isDesktopSlug=slug=>slug==='desktop-shell'||slug.startsWith('desktop-');
let platform=(()=>{ try{return sessionStorage.getItem(PLATFORM_KEY)||'mobile'}catch(e){return 'mobile'} })();
let dapp=(()=>{
  try{
    const v=sessionStorage.getItem(DAPP_KEY);
    return DESKTOP_APPS[v]?v:'fan';
  }catch(e){return 'fan'}
})();
const appOfSlug=slug=>{
  if(slug==='desktop-shell'||slug.startsWith('desktop-fan-')) return 'fan';
  if(slug.startsWith('desktop-management-')) return 'management';
  if(slug.startsWith('desktop-dsc-')) return 'dsc';
  const s=SCREENS.find(x=>x.slug===slug);
  return (s&&s.desktopApp)||'fan';
};
const visibleScreens=()=>{
  if(platform!=='desktop') return SCREENS.filter(s=>!isDesktopSlug(s.slug));
  return SCREENS.filter(s=>DESKTOP_APPS[dapp].match(s));
};
function syncDappUi(){
  document.querySelectorAll('#dapp .dapp__b').forEach(b=>{
    b.setAttribute('aria-pressed', b.dataset.dapp===dapp ? 'true' : 'false');
  });
  document.body.dataset.dapp=dapp;
}
function setDesktopApp(next,navigate=true){
  dapp=DESKTOP_APPS[next]?next:'fan';
  try{sessionStorage.setItem(DAPP_KEY,dapp)}catch(e){}
  syncDappUi();
  nav();
  if(navigate){
    const home=DESKTOP_APPS[dapp].home;
    if(byId[home]) go(home);
    else{
      const first=visibleScreens()[0];
      if(first) go(first.id);
    }
  }
}
function setPlatform(next,navigate=true){
  platform=next==='desktop'?'desktop':'mobile';
  try{sessionStorage.setItem(PLATFORM_KEY,platform)}catch(e){}
  const m=$('#platMobile'), d=$('#platDesktop');
  if(m) m.setAttribute('aria-pressed',platform==='mobile'?'true':'false');
  if(d) d.setAttribute('aria-pressed',platform==='desktop'?'true':'false');
  document.body.dataset.platform=platform;
  syncDappUi();
  nav();
  if(navigate){
    if(platform==='desktop'){
      const home=DESKTOP_APPS[dapp].home;
      if(byId[home]) go(home);
      else{ const first=visibleScreens()[0]; if(first) go(first.id); }
    }else{
      const home=byId[MOBILE_HOME]?MOBILE_HOME:visibleScreens()[0]?.id;
      if(home) go(home);
    }
  }
}
$('#platMobile')?.addEventListener('click',()=>setPlatform('mobile'));
$('#platDesktop')?.addEventListener('click',()=>setPlatform('desktop'));
document.querySelectorAll('#dapp .dapp__b').forEach(b=>{
  b.addEventListener('click',()=>{
    if(platform!=='desktop') setPlatform('desktop',false);
    setDesktopApp(b.dataset.dapp);
  });
});

/* Screenshot pages reference desktop-shots/… — rewrite to an absolute URL
   so images still load inside srcdoc iframes. */
function absolutize(html){
  const base=location.origin+location.pathname.replace(/[^/]*$/,'');
  return html.replace(/(src=["'])desktop-shots\//g,'$1'+base+'desktop-shots/');
}

function go(id,push=true){
  const s=byId[id]; if(!s) return;
  /* Keep platform + desktop-app switches in sync with deep links. */
  if(isDesktopSlug(s.slug)){
    if(platform!=='desktop') setPlatform('desktop',false);
    const want=appOfSlug(s.slug);
    if(want!==dapp){ dapp=want; try{sessionStorage.setItem(DAPP_KEY,dapp)}catch(e){} syncDappUi(); }
  }else if(platform!=='mobile'){
    setPlatform('mobile',false);
  }
  const first=!cur||cur.slug!==s.slug;
  cur=s;
  if(push&&location.hash.slice(1)!==id) history.pushState({},'','#'+id);

  $('#sheet').classList.add('hidden'); $('#dev').classList.remove('hidden');
  $('#crumb').textContent=`${s.group} · ${s.comp}`;
  $('#title').textContent=s.frame;
  const pb=$('#pflag');
  pb.classList.toggle('hidden',!s.proposal);
  $('#pwhy').classList.toggle('hidden',!s.proposal);
  if(s.proposal) $('#pwhy').textContent=s.why;
  $('#dev').classList.toggle('dev--wide',!!s.wide);

  if(first){
    $('#fr').srcdoc=shim(absolutize(DOCS[s.slug]));   /* shim posts {t:'ready'} when listening */
  }else{ frame(s.idx); }

  states(); nav(); notes(); fit();   /* fit last — states() changes the stage height */
  const list=visibleScreens();
  const i=list.indexOf(s);
  $('#prev').disabled=i<=0; $('#next').disabled=i<0||i>=list.length-1;
}

/* inject a shim that shows one frame and reports clicks up to the parent    */
function shim(doc){
  const add=`
<style id="__proto">
  /* One frame visible at a time — works for mobile (main.screen) and
     desktop (main.page). Without this, desktop-shell stacks every state
     into one long scroll. */
  main>section.frame{display:none!important}
  main>section.frame.__on{display:block!important}
  [data-proto-hot]{cursor:pointer}
  /* Specimen captions stay in the review sheets; hide them in the live device. */
  .cap,.framelabel{display:none!important}
</style>
<script>
(function(){
  var F=function(){return [].slice.call(document.querySelectorAll('main>section.frame'))};
  function show(i){var f=F(); if(!f.length)return;
    if(i<0||i>=f.length)i=0;
    f.forEach(function(el,n){el.classList.toggle('__on',n===i)});
    var sc=document.querySelector('.mk__scroll')||document.scrollingElement;
    if(sc)sc.scrollTop=0;
  }
  var HOT=[];
  function wire(list){
    HOT=list||[];
    document.querySelectorAll('[data-proto-hot]').forEach(function(el){
      el.removeAttribute('data-proto-hot')});
    HOT.forEach(function(h){
      try{document.querySelectorAll(h.sel).forEach(function(el){
        el.setAttribute('data-proto-hot',h.to)})}catch(e){}
    });
  }
  document.addEventListener('click',function(e){
    var el=e.target.closest?e.target.closest('[data-proto-hot]'):null;
    if(el){e.preventDefault();parent.postMessage({t:'go',to:el.getAttribute('data-proto-hot')},'*');}
  },true);
  window.addEventListener('message',function(e){
    var d=e.data||{};
    if(d.t==='frame')show(d.i);
    if(d.t==='hot')wire(d.list);
  });
  show(0);
  /* Tell the parent we are listening. Posting frame/hot on the iframe's load event
     raced this listener's registration: whichever message arrived first was dropped,
     which left screens showing frame 0 with no hotspots, intermittently. */
  parent.postMessage({t:'ready'},'*');
})();
<\/script>`;
  return doc.replace('</body>',add+'</body>');
}

function frame(i){
  const w=$('#fr').contentWindow; if(!w) return;
  w.postMessage({t:'frame',i:i<0?0:i},'*');
  w.postMessage({t:'hot',list:FLOWS[cur.id]||FLOWS[cur.slug]||[]},'*');
  setTimeout(designNote,0);
}

/* Lift the frame's own reviewer caption out of the phone and into the side panel. */
function designNote(){
  const box=$('#note'); box.textContent=''; box.classList.add('hidden');
  let d; try{ d=$('#fr').contentDocument }catch(e){ return }
  if(!d) return;
  const on=d.querySelector('main>section.frame.__on')||d.querySelector('main');
  const cap=on&&on.querySelector('.cap');
  if(!cap) return;
  /* the spec id sits in its own span with no whitespace after it, so textContent alone
     yields "CA-08Six cells…" — pull it out and re-join with a separator */
  const c=cap.cloneNode(true);
  const id=c.querySelector('.cap__id');
  let tag=''; if(id){tag=id.textContent.trim(); id.remove();}
  const rest=c.textContent.replace(/\s+/g,' ').trim();
  const t=tag?`${tag} — ${rest}`:rest;
  if(!rest) return;
  box.textContent=t; box.classList.remove('hidden');
}

window.addEventListener('message',e=>{
  const d=e.data||{};
  if(d.t==='go'&&byId[d.to]) go(d.to);
  /* the newly-mounted document is listening — now it is safe to send frame + hotspots */
  if(d.t==='ready'&&cur) frame(cur.idx);
});

/* scale the device so it always fits ------------------------------------- */
function fit(){
  const h=$('#hold'), d=$('#dev');
  d.style.transform='none';
  const pad=44;
  const sy=(h.clientHeight-pad)/d.offsetHeight, sx=(h.clientWidth-pad)/d.offsetWidth;
  const s=Math.min(1,sy,sx);
  d.style.transform=s<1?`scale(${s})`:'none';
}
/* The states row wraps to 1-3 lines depending on the component, so the stage height
   changes as you navigate. Observing the holder is exact; calling fit() from go() raced
   the row's own layout and silently left the device unscaled and clipped. */
new ResizeObserver(()=>{if(cur&&!$('#dev').classList.contains('hidden'))fit()}).observe($('#hold'));

/* left nav ---------------------------------------------------------------- */
function nav(){
  const q=($('#find').value||'').toLowerCase().trim();
  const box=$('#navlist'); box.innerHTML='';
  GROUPS.forEach(g=>{
    const items=g.items.filter(it=>{
      if(platform==='desktop'){
        const probe={slug:it.slug, desktopApp:it.desktopApp||''};
        if(!DESKTOP_APPS[dapp].match(probe)) return false;
      }else if(isDesktopSlug(it.slug)){
        return false;
      }
      if(!q)return true;
      const fs=it.frames.length?it.frames:[it.title];
      return it.title.toLowerCase().includes(q)||g.name.toLowerCase().includes(q)
        ||fs.some(f=>f.toLowerCase().includes(q));
    });
    if(!items.length)return;
    const gd=document.createElement('div'); gd.className='grp';
    gd.innerHTML=`<p class="grp__t">${g.name}</p>`;
    items.forEach(it=>{
      const fs=it.frames.length?it.frames:[it.title];
      const open=q?true:(cur&&cur.slug===it.slug);
      const d=document.createElement('div'); d.className='cmp';
      const unread=fs.reduce((a,_,i)=>a+count(it.frames.length?`${it.slug}/${i}`:it.slug),0);
      d.innerHTML=`<button class="cmp__b" aria-expanded="${open}">
        <span>${it.title}</span>
        ${it.status==='proposal'?'<span class="cmp__p" title="Proposal — no counterpart in the app">P</span>':''}
        ${it.kit?'<span class="cmp__k">KIT</span>':''}
        <span class="cmp__cnt">${unread?unread+'●':fs.length}</span></button>
        <ul class="frames" ${open?'':'hidden'}></ul>`;
      const ul=d.querySelector('.frames');
      fs.forEach((t,i)=>{
        const id=it.frames.length?`${it.slug}/${i}`:it.slug;
        if(q&&!(t.toLowerCase().includes(q)||it.title.toLowerCase().includes(q)
              ||g.name.toLowerCase().includes(q)))return;
        const li=document.createElement('li');
        const isP=!/\bshipped\b/i.test(t)&&(it.status==='proposal'||!!(it.proposalFrames||{})[t]);
        li.innerHTML=`<button class="fr__b" data-id="${id}"
           ${cur&&cur.id===id?'aria-current="true"':''}>
           <span class="fr__n">${String(i+1).padStart(2,'0')}</span><span>${t}</span>
           ${isP?'<span class="fr__p" title="Proposal — no counterpart in the app">P</span>':''}
           ${count(id)?'<span class="fr__dot" title="has comments"></span>':''}</button>`;
        li.querySelector('button').onclick=()=>go(id);
        ul.appendChild(li);
      });
      d.querySelector('.cmp__b').onclick=()=>{
        const h=ul.hasAttribute('hidden');
        if(h){ul.removeAttribute('hidden')}else{ul.setAttribute('hidden','')}
        d.querySelector('.cmp__b').setAttribute('aria-expanded',h);
      };
      gd.appendChild(d);
    });
    box.appendChild(gd);
  });
}
$('#find').oninput=nav;

/* state switcher ---------------------------------------------------------- */
function states(){
  const box=$('#states'); box.innerHTML='';
  const it=GROUPS.flatMap(g=>g.items).find(i=>i.slug===cur.slug);
  if(!it||it.frames.length<2){$('#hint').textContent='';return;}
  it.frames.forEach((t,i)=>{
    const b=document.createElement('button');
    const isP=!/\bshipped\b/i.test(t)&&(it.status==='proposal'||!!(it.proposalFrames||{})[t]);
    b.className='st'+(isP?' st--p':'');
    if(isP)b.title='Proposal — no counterpart in the app';
    b.innerHTML=`<span class="st__n">${String(i+1).padStart(2,'0')}</span>${t}`;
    if(i===cur.idx)b.setAttribute('aria-current','true');
    b.onclick=()=>go(`${cur.slug}/${i}`);
    box.appendChild(b);
  });
  $('#hint').textContent=`${it.frames.length} states · use ← → or the chips above`;
}

/* comments ---------------------------------------------------------------- */
function notes(){
  showingAll=false;
  if(!jCur) $('#jnote').classList.add('hidden');
  $('#for').textContent=`${cur.comp} · ${cur.frame}`;
  render();
}
function render(){
  const l=$('#list'); l.innerHTML='';
  const rows=showingAll
    ? Object.entries(DB).flatMap(([id,cs])=>cs.map(c=>({...c,id2:id})))
    : (DB[cur.id]||[]).map(c=>({...c,id2:cur.id}));
  if(!rows.length){l.innerHTML='<p class="none">No comments yet.</p>';return;}
  rows.sort((a,b)=>b.ts-a.ts).forEach(c=>{
    const d=document.createElement('div'); d.className='cmt'+(c.done?' done':'');
    const s=byId[c.id2];
    d.innerHTML=`<div class="cmt__m">
        <span>${c.who||'anon'}</span><span>·</span><span>${new Date(c.ts).toLocaleString()}</span>
        ${showingAll&&s?`<span>· ${s.comp} / ${s.frame}</span>`:''}
        <button class="cmt__x" title="Delete">×</button></div><p></p>`;
    d.querySelector('p').textContent=c.text;
    d.querySelector('.cmt__x').onclick=()=>{
      DB[c.id2]=(DB[c.id2]||[]).filter(x=>x.ts!==c.ts); if(!DB[c.id2].length)delete DB[c.id2];
      if(c.audio) ADB.del(c.id2+'|'+c.ts);
      save(); render(); nav();
    };
    if(c.audio){
      const pb=document.createElement('button');
      pb.className='cmt__play'; pb.type='button';
      pb.innerHTML='<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M7 4l13 8-13 8z" fill="currentColor"/></svg>'
        +'Voice note · '+fmt(c.audio.ms);
      pb.onclick=async e=>{
        e.stopPropagation();
        const b=await ADB.get(c.id2+'|'+c.ts);
        if(!b){ pb.textContent='Recording not found'; return; }
        const a=new Audio(URL.createObjectURL(b)); a.play();
      };
      d.appendChild(pb);
    }
    d.onclick=e=>{ if(e.target.closest('.cmt__x'))return;
      const t=(DB[c.id2]||[]).find(x=>x.ts===c.ts); if(t){t.done=!t.done;save();render();nav();} };
    l.appendChild(d);
  });
}

/* ------------------------------------------------- dictation + voice notes */
/* Audio lives in IndexedDB, not localStorage: a minute of Opus is ~100 KB and
   localStorage is a ~5 MB string store shared with the comments themselves. */
const ADB={
  db:null,
  open(){ return this.db?Promise.resolve(this.db):new Promise((res,rej)=>{
    const r=indexedDB.open('sh-proto-audio',1);
    r.onupgradeneeded=()=>r.result.createObjectStore('clips');
    r.onsuccess=()=>{this.db=r.result;res(this.db)}; r.onerror=()=>rej(r.error);
  })},
  async put(k,b){const db=await this.open();return new Promise((res,rej)=>{
    const tx=db.transaction('clips','readwrite');tx.objectStore('clips').put(b,k);
    tx.oncomplete=res;tx.onerror=()=>rej(tx.error)})},
  async get(k){const db=await this.open();return new Promise((res)=>{
    const r=db.transaction('clips').objectStore('clips').get(k);
    r.onsuccess=()=>res(r.result||null);r.onerror=()=>res(null)})},
  async del(k){const db=await this.open();return new Promise((res)=>{
    const tx=db.transaction('clips','readwrite');tx.objectStore('clips').delete(k);
    tx.oncomplete=res;tx.onerror=res})}
};

const canMic = window.isSecureContext && !!(navigator.mediaDevices||{}).getUserMedia
               && typeof MediaRecorder!=='undefined';
const SR = window.SpeechRecognition||window.webkitSpeechRecognition;

function vhint(msg){ const h=$('#vhint');
  if(!msg){h.classList.add('hidden');return}
  h.textContent=msg; h.classList.remove('hidden'); }

if(!canMic && !SR){
  $('#dictate').disabled=true; $('#record').disabled=true;
  vhint(location.protocol==='file:'
    ? 'Dictation and recording need the prototype served over http — open it from a local server rather than by double-clicking the file. Typing works either way.'
    : 'This browser will not give the page a microphone. Typing works.');
}else{
  if(!SR){ $('#dictate').disabled=true; $('#dictate').title='This browser has no speech recognition';
    $('#record').title='Voice notes stay in this browser — the export mentions them but does not contain the audio.'; }
  if(!canMic){ $('#record').disabled=true; $('#record').title='No microphone available to this page'; }
}

/* ---- dictation: writes into the textarea so it can be edited before saving ---- */
let rec=null, recOn=false, dictBase='';
if(SR){
  $('#dictate').onclick=()=>{
    if(recOn){ rec.stop(); return; }
    rec=new SR(); rec.continuous=true; rec.interimResults=true; rec.lang='en-GB';
    dictBase=$('#txt').value ? $('#txt').value.replace(/\s+$/,'')+' ' : '';
    rec.onresult=e=>{
      let fin='', mid='';
      for(let i=e.resultIndex;i<e.results.length;i++){
        const r=e.results[i];
        if(r.isFinal) fin+=r[0].transcript; else mid+=r[0].transcript;
      }
      if(fin) dictBase=(dictBase+fin).replace(/\s+/g,' ').replace(/^\s/,'')+' ';
      $('#txt').value=(dictBase+mid).trimEnd();
    };
    rec.onerror=e=>{ vhint(e.error==='not-allowed'
      ? 'Microphone permission was refused. Allow it in the address bar, then try again.'
      : 'Dictation stopped: '+e.error); stopDict(); };
    rec.onend=stopDict;
    rec.start(); recOn=true;
    $('#dictate').classList.add('on'); $('#dictateL').textContent='Stop';
    vhint('Listening — speak, then press Stop. The text lands in the box above and you can edit it.');
  };
}
function stopDict(){ recOn=false; $('#dictate').classList.remove('on');
  $('#dictateL').textContent='Dictate'; $('#txt').focus(); }

/* ---- audio recording ---- */
/* SpeechRecognition cannot transcribe a saved blob, so a second recogniser runs
   alongside MediaRecorder while the reviewer speaks. The transcript is what
   travels in the export; the audio itself never leaves this browser. */
let mr=null, chunks=[], pendBlob=null, pendMs=0, t0=0, tick=null, vrec=null, vtx='';
const cleanTx=()=>vtx.replace(/\s+/g,' ').trim();
$('#record').onclick=async()=>{
  if(mr && mr.state==='recording'){ mr.stop(); return; }
  try{
    const stream=await navigator.mediaDevices.getUserMedia({audio:true});
    const mime=MediaRecorder.isTypeSupported('audio/webm;codecs=opus')?'audio/webm;codecs=opus'
              :(MediaRecorder.isTypeSupported('audio/mp4')?'audio/mp4':'');
    mr=new MediaRecorder(stream, mime?{mimeType:mime}:undefined);
    chunks=[]; t0=Date.now(); vtx=''; vrec=null;
    /* live transcript — skipped if dictation already holds the recogniser */
    if(SR && !recOn){ try{
      vrec=new SR(); vrec.continuous=true; vrec.interimResults=false; vrec.lang='en-GB';
      vrec.onresult=e=>{ for(let i=e.resultIndex;i<e.results.length;i++)
        if(e.results[i].isFinal) vtx+=e.results[i][0].transcript+' '; };
      vrec.onerror=()=>{}; vrec.start();
    }catch(e){ vrec=null; } }
    mr.ondataavailable=e=>{ if(e.data.size) chunks.push(e.data) };
    mr.onstop=()=>{
      stream.getTracks().forEach(t=>t.stop());
      if(vrec){ try{vrec.stop()}catch(e){} }
      pendMs=Date.now()-t0;
      pendBlob=new Blob(chunks,{type:mr.mimeType||'audio/webm'});
      $('#pendA').src=URL.createObjectURL(pendBlob);
      $('#pend').classList.remove('hidden');
      $('#record').classList.remove('on'); $('#recordL').textContent='Record';
      clearInterval(tick);
      vhint(vrec
        ? 'Recording attached, transcript captured — the transcript travels in the export; the audio stays in this browser.'
        : 'Recording attached — it stays in this browser, and the export will only note that it exists. Add a text note above if the feedback needs to travel.');
    };
    mr.start();
    $('#record').classList.add('on');
    tick=setInterval(()=>{ $('#recordL').textContent='Stop '+fmt(Date.now()-t0) },250);
    vhint(vrec
      ? 'Recording and transcribing — press Stop when you are done. The transcript travels in the export; the audio stays in this browser.'
      : 'Recording — press Stop when you are done. Voice notes stay in this browser; if the feedback must reach us, use Dictate instead.');
  }catch(e){
    vhint(e && e.name==='NotAllowedError'
      ? 'Microphone permission was refused. Allow it in the address bar, then try again.'
      : 'Could not start recording: '+(e&&e.name||e));
  }
};
$('#pendX').onclick=()=>{ pendBlob=null; pendMs=0; vtx=''; vrec=null;
  $('#pend').classList.add('hidden'); $('#pendA').removeAttribute('src'); vhint(''); };
const fmt=ms=>{const s=Math.round(ms/1000);return Math.floor(s/60)+':'+String(s%60).padStart(2,'0')};

$('#add').onclick=async()=>{
  const t=$('#txt').value.trim(); if((!t&&!pendBlob)||!cur)return;
  const ts=Date.now();
  if(pendBlob){ try{ await ADB.put(cur.id+'|'+ts,pendBlob) }catch(e){
    vhint('The recording could not be stored — the note was saved as text only.'); } }
  const tx=pendBlob?cleanTx():'';
  (DB[cur.id]=DB[cur.id]||[]).push({
    text:t||tx||'(voice note)', who:$('#who').value.trim(), ts, done:false,
    audio: pendBlob?{ms:pendMs,type:pendBlob.type,tx:(t&&tx)?tx:''}:null });
  save(); $('#txt').value=''; $('#pendX').click(); render(); nav();
};
$('#txt').onkeydown=e=>{if((e.metaKey||e.ctrlKey)&&e.key==='Enter')$('#add').click()};
$('#allc').onclick=()=>{showingAll=!showingAll;$('#for').textContent=showingAll
  ?'Every comment':`${cur.comp} · ${cur.frame}`;render()};

$('#exp').onclick=()=>{
  const out=['# SportsHeist prototype — client comments','',
    `_Exported ${new Date().toLocaleString()}_`,''];
  let n=0;
  SCREENS.forEach(s=>{
    const cs=DB[s.id]; if(!cs||!cs.length)return;
    out.push(`## ${s.group} · ${s.comp} — ${s.frame}`,`\`#${s.id}\``,'');
    cs.slice().sort((a,b)=>a.ts-b.ts).forEach(c=>{
      n++; out.push(`- ${c.done?'~~':''}${c.text}${c.done?'~~':''}`,
        `  — ${c.who||'anon'}, ${new Date(c.ts).toLocaleString()}`
        + (c.audio?` · voice note ${fmt(c.audio.ms)} (audio stays in the browser`
          + (c.audio.tx?`; transcript: "${c.audio.tx}")`:', not in this file)'):''));
    });
    out.push('');
  });
  if(!n){alert('No comments to export yet.');return;}
  const b=new Blob([out.join('\n')],{type:'text/markdown'});
  const a=document.createElement('a');
  a.href=URL.createObjectURL(b); a.download='sportsheist-comments.md'; a.click();
  URL.revokeObjectURL(a.href);
};

/* coverage ---------------------------------------------------------------- */
$('#cov').onclick=()=>{
  $('#dev').classList.add('hidden');
  const s=$('#sheet'); s.classList.remove('hidden');
  $('#crumb').textContent='Prototype'; $('#title').textContent='Coverage';
  const kits=SCREENS.filter(x=>x.kit).length;
  s.innerHTML=`<h2>What is in this prototype</h2>
  <p><b>${GROUPS.flatMap(g=>g.items).length} components · ${SCREENS.length} screens.</b>
  Every screen is the real rebuilt component, running live — not a picture of one.
  ${kits} of them are specimen sheets (marked <span class="tag">KIT</span> in the menu) rather than
  screens a member navigates to.</p>
  <h3>By section</h3>
  <table><thead><tr><th>Section</th><th>Components</th><th>Screens</th></tr></thead><tbody>
  ${GROUPS.map(g=>`<tr><td>${g.name}</td><td>${g.items.length}</td>
    <td>${g.items.reduce((a,i)=>a+(i.frames.length||1),0)}</td></tr>`).join('')}
  </tbody></table>
  <h3>Known gaps</h3>
  <p>These are recorded in <code>Screen-Specs/00-COVERAGE-AUDIT.md</code>, which is generated from
  the filesystem by <code>_assets/coverage.py</code>.</p>
  <table><thead><tr><th>Area</th><th>Status</th></tr></thead><tbody>
  <tr><td><code>internalUser</code>, <code>customerUser</code> trees (6 routes)</td>
      <td><span class="tag tag--no">Not built</span> Foreign scaffolding — hardcoded Vietnamese and a
      <code>'Farmer Side'</code> role. Slated for deletion, not rebranding.</td></tr>
  <tr><td><code>myAccountInfo</code>, <code>myAccountPass</code></td>
      <td><span class="tag tag--no">Not built</span> Same scaffolding, reachable only through a drawer
      whose only caller is an unrouted stub page.</td></tr>
  <tr><td><code>detailData</code>, <code>childAccountDetail</code></td>
      <td><span class="tag">n/a</span> Declared route strings with no widget and no <code>GoRoute</code>.</td></tr>
  <tr><td>Matches tab body</td>
      <td><span class="tag tag--no">Empty in code</span> <code>matches_body.dart:14</code> renders
      <code>Container()</code>. The rebuilt Matches screens are a proposal, not a transcription.</td></tr>
  </tbody></table>
  <h3>Decisions still open</h3>
  <p>Three contradictions in the library need your ruling before build:
  <b>Merit detail vs Hall of Fame</b> (one assumes a single badge collection replaces the Achievements
  tabs, the other assumes both survive); <b>Linked member vs Child accounts</b> (the first is now a
  strict subset of the second, and uses different vocabulary); and whether the
  <b>child-account and add-club flows are desktop-only</b> — the mobile code has no payment path and
  its own copy says "log in to sports heist on desktop".</p>`;
};


/* ---------------------------------------------------------------- journeys */
const JLIST=[];
(JOURNEYS||[]).forEach(g=>(g.journeys||[]).forEach(j=>JLIST.push({...j,group:g.name})));
let jCur=null, jStep=0;

function jOpen(){
  $('#jpick').classList.remove('hidden');
  jRender(); $('#jfind').focus();
}
function jRender(){
  const q=($('#jfind').value||'').toLowerCase().trim();
  const box=$('#jlist'); box.innerHTML='';
  if(!JLIST.length){
    box.innerHTML='<p class="none">No journeys defined yet. They live in '+
      '<code>_assets/journeys.json</code>.</p>'; return;
  }
  const groups={};
  JLIST.forEach(j=>{
    if(q && !((j.name+' '+(j.who||'')+' '+(j.why||'')+' '+j.group).toLowerCase().includes(q))) return;
    (groups[j.group]=groups[j.group]||[]).push(j);
  });
  const names=Object.keys(groups);
  if(!names.length){box.innerHTML='<p class="none">Nothing matches.</p>';return}
  names.forEach(n=>{
    const d=document.createElement('div'); d.className='jgrp';
    d.innerHTML=`<p class="jgrp__t">${n} · ${groups[n].length}</p>`;
    groups[n].forEach(j=>{
      const b=document.createElement('button'); b.className='jrow'; b.type='button';
      const bad=(j.steps||[]).filter(s=>!byId[s.screen]).length;
      b.innerHTML=`<span><span class="jrow__n">${j.name}</span>
        ${j.who?`<span class="jrow__w"> · ${j.who}</span>`:''}
        ${j.why?`<span class="jrow__y">${j.why}</span>`:''}</span>
        <span class="jrow__c">${(j.steps||[]).length} steps${bad?' · '+bad+' missing':''}</span>`;
      b.onclick=()=>{ $('#jpick').classList.add('hidden'); jStart(j); };
      d.appendChild(b);
    });
    box.appendChild(d);
  });
}
function jStart(j){ jCur=j; jStep=0; jGo(0); }
function jGo(n){
  if(!jCur) return;
  const steps=(jCur.steps||[]).filter(s=>byId[s.screen]);
  if(!steps.length){ jExit(); return; }
  jStep=Math.max(0,Math.min(n,steps.length-1));
  const s=steps[jStep];
  $('#jbar').classList.remove('hidden');
  $('#jname').textContent=jCur.name;
  $('#jwho').textContent=[jCur.group,jCur.who].filter(Boolean).join(' · ');
  $('#jstep').textContent=`Step ${jStep+1} of ${steps.length}`;
  $('#jprev').disabled=jStep===0;
  $('#jnext').textContent = jStep===steps.length-1 ? 'Done' : 'Next →';
  go(s.screen);
  const note=$('#jnote');
  if(s.note){ note.textContent=s.note; note.classList.remove('hidden'); }
  else note.classList.add('hidden');
}
function jExit(){
  jCur=null; $('#jbar').classList.add('hidden'); $('#jnote').classList.add('hidden');
}
$('#jbtn').onclick=jOpen;
$('#jclose').onclick=()=>$('#jpick').classList.add('hidden');
$('#jfind').oninput=jRender;
$('#jx').onclick=jExit;
$('#jprev').onclick=()=>jGo(jStep-1);
$('#jnext').onclick=()=>{
  const steps=(jCur.steps||[]).filter(s=>byId[s.screen]);
  if(jStep>=steps.length-1) jExit(); else jGo(jStep+1);
};

/* keys + routing ---------------------------------------------------------- */
addEventListener('keydown',e=>{
  if(/^(INPUT|TEXTAREA)$/.test(e.target.tagName))return;
  if(jCur){                      /* in playback the arrows step the journey, not the library */
    const steps=(jCur.steps||[]).filter(s=>byId[s.screen]);
    if(e.key==='ArrowRight'){ if(jStep<steps.length-1) jGo(jStep+1); return; }
    if(e.key==='ArrowLeft'){ if(jStep>0) jGo(jStep-1); return; }
    if(e.key==='Escape'){ jExit(); return; }
  }
  const list=visibleScreens();
  const i=list.indexOf(cur);
  if(e.key==='ArrowRight'&&i>=0&&i<list.length-1)go(list[i+1].id);
  if(e.key==='ArrowLeft'&&i>0)go(list[i-1].id);
});
$('#prev').onclick=()=>{const list=visibleScreens();const i=list.indexOf(cur);if(i>0)go(list[i-1].id)};
$('#next').onclick=()=>{const list=visibleScreens();const i=list.indexOf(cur);if(i>=0&&i<list.length-1)go(list[i+1].id)};
addEventListener('popstate',()=>{const id=location.hash.slice(1);if(byId[id])go(id,false)});

/* Boot: honour hash, else open the home screen for the saved platform. */
(function boot(){
  const hash=location.hash.slice(1);
  if(byId[hash]){
    if(isDesktopSlug(byId[hash].slug)){
      dapp=appOfSlug(byId[hash].slug);
      try{sessionStorage.setItem(DAPP_KEY,dapp)}catch(e){}
      setPlatform('desktop',false);
    }else{
      setPlatform('mobile',false);
    }
    go(hash,false);
    return;
  }
  setPlatform(platform,false);
  syncDappUi();
  const home=platform==='desktop'
    ?(byId[DESKTOP_APPS[dapp].home]?DESKTOP_APPS[dapp].home:visibleScreens()[0]?.id)
    :(byId[MOBILE_HOME]?MOBILE_HOME:visibleScreens()[0]?.id);
  if(home) go(home,false);
})();
"""

if __name__ == "__main__":
    build()
