#!/usr/bin/env python3
"""Regenerate the Rebuilt? column of 00-COVERAGE-AUDIT.md from the filesystem.

The Rebuilt? column used to be hand-written prose. It drifted: it still claimed
`launch`, `all-locker-rooms`, `locker-room-editor` and `action-detail` had no HTML
long after all four were built, which is how ~27 fully-specified profile screens got
missed. Nothing here is typed by hand except ROUTE_SLUGS — the rest is measured.

Run from the components directory:  python3 _assets/coverage.py
Add --check to fail instead of writing (for a pre-flight).
"""
import json
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
COMPONENTS = os.path.dirname(HERE)
AUDIT = os.path.normpath(
    os.path.join(COMPONENTS, "..", "..", "Screen-Specs", "00-COVERAGE-AUDIT.md")
)

# The ONLY hand-maintained thing in this file: which component(s) rebuild each route.
# A route absent from this map is reported as unmapped rather than silently passing.
ROUTE_SLUGS = {
    "splash": ["launch"],
    "introduction": ["auth"],
    "login": ["auth"],
    "preLogin": ["auth"],
    "register": ["onboarding"],
    "forgotPassword": ["auth"],
    "otpVerification": ["auth"],
    "resetPassword": ["auth"],
    "home": ["foundations", "desktop-shell"],
    "allLockerRooms": ["all-locker-rooms"],
    "lockerRoomEditor": ["locker-room-editor"],
    "profileSetting": ["account-settings"],
    "changePassword": ["account-settings"],
    "achievement": ["hall-of-fame", "merit-detail", "profile"],
    "myChildAccount": ["child-account", "linked-member"],
    "ideas": ["idea-card", "ideas-list", "war-room"],
    "voting": ["voting-card", "voting-list", "war-room"],
    "results": ["results-actions"],
    "actions": ["results-actions"],
    "actionDetail": ["action-detail"],
    "likeCount": ["idea-detail", "comments"],
    "voteCount": ["proposal-detail", "comments"],
    "resultDetail": ["results-actions"],
    "vetoHold": ["veto"],
    "confirmReject": ["veto"],
    "warningIdea": ["idea-gate"],
    "createIdeas": ["create-idea"],
    "security": ["account-settings"],
    "notificationSetting": ["account-settings"],
    "creditTransaction": ["wallet"],
}

# Routes deliberately NOT rebuilt, with the reason. These are not gaps.
FOREIGN = {
    "internalUser", "createInternalUser", "internalUserDetails",
    "customerUser", "createCustomerUser", "customerUserDetails",
    "myAccountInfo", "myAccountPass",
}
NO_WIDGET = {"detailData", "childAccountDetail"}

BEGIN = "<!-- BEGIN GENERATED: coverage.py -->"
END = "<!-- END GENERATED: coverage.py -->"


def built():
    """slug -> frame count, for every manifest entry with both files on disk."""
    man = json.load(open(os.path.join(HERE, "manifest.json")))
    out = {}
    for group in man["groups"]:
        for item in group["items"]:
            slug = item["slug"]
            html = os.path.join(COMPONENTS, f"{slug}.html")
            notes = os.path.join(COMPONENTS, f"{slug}.notes.html")
            if os.path.exists(html) and os.path.exists(notes):
                frames = len(re.findall(r'class="frame"', open(html).read()))
                out[slug] = frames or 1
    return out


def cell(route, have):
    if route in NO_WIDGET:
        return "n/a — no widget"
    if route in FOREIGN:
        return "**No** — foreign scaffolding, slated for deletion"
    slugs = ROUTE_SLUGS.get(route)
    if not slugs:
        return "**UNMAPPED** — add it to `coverage.py`"
    missing = [s for s in slugs if s not in have]
    if missing:
        return "**No** — " + ", ".join(f"`{s}` not built" for s in missing)
    return "Yes — " + ", ".join(f"`{s}.html`" for s in slugs)


def main():
    have = built()
    src = open(AUDIT).read()
    lines = src.split("\n")
    changed, unmapped = [], []

    for n, line in enumerate(lines):
        if not line.startswith("| "):
            continue
        cols = [c.strip() for c in line.strip().strip("|").split("|")]
        # The route table has exactly 9 columns and a `name → path` in column 2.
        # The tab-body table below it has 8 and a bare widget name — an earlier
        # version matched it too and overwrote its Notes column with garbage.
        if len(cols) != 9 or not cols[0].isdigit() or "→" not in cols[1]:
            continue
        route = re.sub(r"`|\s*→.*", "", cols[1]).strip()
        new = cell(route, have)
        if "UNMAPPED" in new:
            unmapped.append(route)
        if cols[7] != new:
            changed.append(f"  {route}: {cols[7][:44]!r} -> {new[:44]!r}")
            cols[7] = new
            lines[n] = "| " + " | ".join(cols) + " |"

    total = sum(have.values())
    block = [
        BEGIN,
        "",
        f"**Generated by `Branding Designs/components/_assets/coverage.py` — do not hand-edit.**",
        "",
        f"- Components built: **{len(have)}**",
        f"- Screens (frames) built: **{total}**",
        f"- Routes deliberately not rebuilt: **{len(FOREIGN)}** (foreign scaffolding) "
        f"+ **{len(NO_WIDGET)}** with no widget at all",
        "",
        "| Component | Frames |",
        "|---|---|",
    ]
    block += [f"| `{s}` | {c} |" for s, c in sorted(have.items())]
    block += ["", END]
    block = "\n".join(block)

    out = "\n".join(lines)
    if BEGIN in out and END in out:
        out = re.sub(re.escape(BEGIN) + r".*?" + re.escape(END), block, out, flags=re.S)
    else:
        out = out.rstrip() + "\n\n## Generated coverage\n\n" + block + "\n"

    if "--check" in sys.argv:
        if out != src or unmapped:
            print("coverage.py: audit is stale — run without --check")
            for c in changed:
                print(c)
            sys.exit(1)
        print("coverage.py: audit is current")
        return

    open(AUDIT, "w").write(out)
    print(f"  {len(have)} components · {total} frames")
    if changed:
        print(f"  rewrote {len(changed)} stale Rebuilt? cells:")
        for c in changed:
            print(c)
    else:
        print("  Rebuilt? column was already current")
    if unmapped:
        print(f"  !! UNMAPPED routes (add to ROUTE_SLUGS): {', '.join(unmapped)}")


if __name__ == "__main__":
    main()
