#!/usr/bin/env python3
"""Merge journeys.*.json into journeys.json, then validate.

The catalogue is authored in per-section files so several people can write at once
without fighting over one JSON blob. This merges them, rejects duplicate ids, drops
steps that point at screens which no longer exist, and reports what it dropped —
silently skipping a bad step would leave the client stepping through a journey with
a hole in it and no way to know.

  python3 _assets/merge-journeys.py            # merge and report
  python3 _assets/merge-journeys.py --strict   # non-zero exit if anything was dropped
"""
import glob
import json
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
OUT = os.path.join(HERE, "journeys.json")

README = ("Named, ordered paths through the prototype, played back with the arrow keys. "
          "GENERATED by merge-journeys.py from journeys.*.json — edit those, not this file.")


def screen_ids():
    """Must mirror frames_of() in build-prototype.py exactly."""
    man = json.load(open(os.path.join(HERE, "manifest.json")))
    out = set()
    for g in man["groups"]:
        for it in g["items"]:
            slug = it["slug"]
            p = os.path.join(ROOT, f"{slug}.html")
            if not os.path.exists(p):
                continue
            src = open(p, encoding="utf-8").read()
            _m = re.search(r"<main[^>]*>(.*)</main>", src, re.S)
            n = len(re.findall(r'<section[^>]*class="[^"]*\bframe\b[^"]*"[^>]*>',
                               _m.group(1) if _m else src))
            if n:
                out.update(f"{slug}/{i}" for i in range(n))
            else:
                out.add(slug)
    return out


def main():
    ids = screen_ids()
    sources = sorted(glob.glob(os.path.join(HERE, "journeys.*.json")))
    sources = [s for s in sources if os.path.basename(s) != "journeys.json"]
    if not sources:
        print("  no journeys.*.json source files found")
        return 0

    groups, seen, dropped, badjourneys, dupes = [], set(), [], [], []
    for src in sources:
        name = os.path.basename(src)
        try:
            data = json.load(open(src, encoding="utf-8"))
        except json.JSONDecodeError as e:
            print(f"  {name}: INVALID JSON — {e}")
            continue
        blocks = data.get("groups", data) if isinstance(data, dict) else data
        for g in blocks:
            keep = []
            for j in g.get("journeys", []):
                jid = j.get("id") or "(no id)"
                if jid in seen:
                    dupes.append(f"{name}: {jid}")
                    continue
                steps = j.get("steps", [])
                good = [s for s in steps if s.get("screen") in ids]
                for s in steps:
                    if s.get("screen") not in ids:
                        dropped.append(f"{name} / {jid} -> {s.get('screen')!r}")
                if len(good) < 2:
                    badjourneys.append(f"{name}: {jid} ({len(good)} usable steps)")
                    continue
                seen.add(jid)
                j["steps"] = good
                keep.append(j)
            if keep:
                groups.append({"name": g.get("name", "Journeys"), "journeys": keep})

    total = sum(len(g["journeys"]) for g in groups)
    steps = sum(len(j["steps"]) for g in groups for j in g["journeys"])
    json.dump({"_readme": README, "groups": groups},
              open(OUT, "w", encoding="utf-8"), indent=1, ensure_ascii=False)
    open(OUT, "a").write("\n")

    print(f"  merged {len(sources)} file(s) -> {len(groups)} groups · {total} journeys · {steps} steps")
    for label, rows in (("dropped step(s) pointing at a missing screen", dropped),
                        ("duplicate journey id(s), skipped", dupes),
                        ("journey(s) skipped for having under 2 usable steps", badjourneys)):
        if rows:
            print(f"  {len(rows)} {label}:")
            for r in rows[:15]:
                print("    " + r)
            if len(rows) > 15:
                print(f"    … and {len(rows)-15} more")
    if not (dropped or dupes or badjourneys):
        print("  nothing dropped — every step resolves and every id is unique")
    return 1 if ("--strict" in sys.argv and (dropped or dupes or badjourneys)) else 0


if __name__ == "__main__":
    sys.exit(main())
